#!/bin/bash

# Install dependencies
function install_dependencies {
	install_from_list "Install dependencies" "dependencies" 
	install_from_list "Install pip dependencies" "dependencies-pip" main
}


# Install preferred utilities
function install_utils {
	install_from_list "preferred utilities" "utils" 
	install_from_list "preferred development tools" "dev-tools" 
	install_from_list "VPN" "vpn" main
	
}

# Snap
function install_snap_utils {
	install_snap_from_list "snap programs" "utils-snap" main
}

# Install preferred GNOME apps
function install_codecs {
	install_package "multimedia codecs" "ubuntu-restricted-extras" main
}

function install_all_utils {
	install_from_list "Install dependencies" "dependencies" 
	install_pip_from_list "pip dependencies" "dependencies-pip" 
  install_pip_from_list "pip tools" "pip-tools"
  install_from_list "preferred utilities" "utils" 
	install_from_list "preferred development tools" "dev-tools" 
        install_from_list "VPN" "vpn" 
	install_snap_from_list "snap programs" "utils-snap" 

}

