#!/bin/bash
#
# When adding (or removing) any functions remember to update
# the 'install_thirdparty' function below to reflect any changes you make

# Automatically import apps functions
function import_apps_functions {
	DIR="functions/apps"
	# iterate through the files in the 'functions/apps' folder
	for FUNCTION in $(dirname "$0")/$DIR/*; do
		if [[ -d $FUNCTION ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
			. $FUNCTION
		fi
	done
}

# Install Third-Party Applications
function install_thirdparty {
	NAME="Third-Party Software"
	DIR="functions/apps"
	
	echo_message title "Starting installation of ${NAME}..."
	import_apps_functions
	
	for APP in $(dirname "$0")/$DIR/*; do
		APP_NAME=$(echo $APP | cut -d'/' -f4)
		install_$APP_NAME
		
	done
}
