#!/bin/bash
#

# Install Third-Party Applications
function install_thirdparty {
	NAME="Third-Party Software"
	DIR="functions/apps"

	echo_message title "Starting installation of ${NAME}..."
	
	# Import thirdparty install functions
	import_functions $DIR

	for APP in $(dirname "$0")/$DIR/*; do
		APP_NAME=$(echo $APP | cut -d'/' -f4)
		install_$APP_NAME
		
	done
}
