#!/bin/bash

# Perform system upgrade via apt
function update_system {
	echo_message title "Performing system update..."
	
	# Update repository information
	echo_message info 'Refreshing repository information...'
	# Admin privileges
	superuser_do 'apt update -y -qq'
	echo_message success 'Repository information updated.'

	# List upgrades
	if [ $(apt list --upgradeable | wc -l) = 1 ]; then
		# Cancelled
		echo_message info "System is up to date."
	else
		# Upgrade
		echo_message info 'Upgrading packages...'
		superuser_do "apt full-upgrade"
	
		# Finished
		echo_message success "System update complete."
		system_update
	fi
}

# Check for snap updates
function update_snap_apps {
	echo_message info "Updating installed snap packages..."
	superuser_do "snap refresh"
	if [ $? = 0 ]; then
		# Finished
		echo_message success "All snaps up to date."
	else
		# Finished
		echo_message success "Snap package update complete."
	fi
}

# Check for flatpak updates
function update_flatpak_apps {
	# continue
	echo_message info "Updating installed flatpak packages..."
	flatpak update
	if [ $? = 0 ]; then
		# Finished
		echo_message success "All flatpaks up to date."
	else
		# Finished
		echo_message success "Flatpak package update complete."
	fi
}

# Update fish and plugins
function update_fish {
	fish -c fisher
	fish -c "omf update"
}

# Update vim plugins
function update_vim {
	vim +PlugUpgrade +qall > /dev/null 
	vim +PlugUpdate +qall > /dev/null 
}

# Perform system updates
function system_update {
	# install
	echo_message title "Starting system updates..."
	update_system
	update_snap_apps
	update_fish 
	update_vim
}
