#!/bin/bash

function install_cool-retro-term {
	echo_message info "Installing cool-retro-terminal..."

	add_launchpad_ppa "cool-retro-terminal " "vantuz/cool-retro-term"
	install_package "Retro Terminal" "cool-retro-term"

  if [ $? == 0 ]; then
    echo_message success "Installation of package cool-retro-terminal is complete."
  fi


}
