#!/bin/bash

function install_neovim {

	echo_message info "Installing NeoVim..."	

	if [ $(check_package_installed neovim) == 0 ]; then
		return	
	fi


	add_launchpad_ppa "NeoVim" "neovim-ppa/stable"
	superuser_do "apt update"
	superuser_do "apt install neovim"
	
	
	
	echo_message info "Setting up NeoVim..."

	# Installing plugin manager vim_plug
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	mkdir $HOME/.config/nvim
	cp $(dirname $0)/data/configs/init.vim $HOME/.config/nvim
	mkdir $HOME/.config/nvim/plugged
	
	vim +PlugInstall +qall > /dev/null

	echo_message success "NeoVim setup finished"
}
