#!/bin/bash

function install_regolith-linux {
	echo_message info "Installing regolith-linux..."	
	
	if [ $(check_package_installed regolith-desktop) == 0 ]; then
		return
	fi

	add_launchpad_ppa "regolith-linux" "kgilmer/regolith-stable"


	superuser_do "apt install regolith-desktop"

	# Finished
        echo_message success "Installation of package regolith-linux is complete."


}
