#!/bin/bash

function setup_scripts {

    echo_message info "Setting up shell scripts..."
  
    mkdir $HOME/.config/scripts
    cp $(dirname $0)/data/scripts/* $HOME/.config/scripts

  echo_message success "Finished setting up shell scripts."
}
