#!/bin/bash 

function stop_iio-sensor {
	# Stops weird screen rotation ubuntu

	echo_message info "Disable iio-sensor.."
	superuser_do "systemctl stop iio-sensor-proxy.service"
	superuser_do "systemctl disable iio-sensor-proxy.service"

	superuser_do "apt remove iio-sensor-proxy"

}
