#!/bin/bash


function setup_fish {

	# Set fish as standart shell
	chsh -s /usr/bin/fish
	
  # Set fish as standart shell for root as well
  superuser_do "chsh -s /usr/bin/fish"

	# Add to /etc/shells
	if [[ $(cat /etc/shells | grep "fish" &> /dev/null; echo $?) != 0 ]]; then
		$(echo /usr/bin/fish | sudo tee -a /etc/shells)
	fi

	
	# Package manager fisher https://github.com/jorgebucaran/fisher
	curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

	# Package manager oh my fish
  curl -L https://get.oh-my.fish | fish

	# Package-dependency: https://github.com/matchai/spacefish (shell prompt)
	install_package "Font powerline" "fonts-powerline"

	# Copy fish config
	cp $(dirname $0)/data/configs/config.fish $HOME/.config/fish/

	# Install fisher plugins 
	fish -c "fisher add franciscolourenco/done"
	fish -c "fisher add joseluisq/gitnow@2.1.1"
	fish -c "fisher add decors/fish-colored-man"

	# Add bobthefish to omf
	fish -c "omf install bobthefish"

}

