#!/bin/bash

function setup_i3blocks {
	echo_message info "Setting up i3blocks..."
 
  superuser_do "cp $(dirname $0)/data/scripts/i3blocks/* /usr/share/i3blocks/"

  superuser_do "cp $(dirname $0)/data/configs/i3blocks.conf /etc" 

  echo_message success "Finished setting up i3blocks."
}
