#!/bin/bash


function setup_neovim {
	echo_message info "Setting up NeoVim..."
  
  # SpaceVim Setup
  
  curl -sLf https://spacevim.org/install.sh | bash

  cp $(dirname $0)/data/configs/init.toml ~/.SpaceVim/init.toml
	# Installing plugin manager vim_plug
	#curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	#mkdir $HOME/.config/nvim
	#cp $(dirname $0)/data/configs/init.vim $HOME/.config/nvim
	#mkdir $HOME/.config/nvim/plugged
	
	#vim +PlugInstall +qall > /dev/null


	echo_message success "Finished setting up NeoVim."

}
