#!/bin/bash


function setup_neovim {
  
	# Installing plugin manager vim_plug
	curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

	# Create NeoVim config folder and add own config
	# TODO symlink config, so changes get saved
	mkdir $HOME/.config/nvim
	cp $(dirname $0)/data/configs/init.vim $HOME/.config/nvim
	mkdir $HOME/.config/nvim/plugged

	# Install the plugins
	vim +PlugInstall +qall > /dev/null

}
